### ISSUE TITLE
Storing Pods

### ISSUE THREAD

**Issue by jasontwong** [verypossible/booster-kit-swift#16]
Should we be storing pods in the repo? One of our projects has gotten extremely large with certain pods and require `git-lfs` to be used. The repo is over 300MB in size now.

**Comment by tpalmer** [comment]
We don't necessarily have to be storing pods in the repo, no.  The reason we started doing it was because CI would run into pod issues when this was first setup.  I'm happy to remove them if it makes things easier, as long as CI/CD works.

**Comment by tpalmer** [comment]
After looking into this a bit, I think a good way to proceed would be to retain the Pods directory for the booster kit, but if a repository becomes really large we could remove it on a per-project basis.  Here are some pros and cons of keeping/removing the Pods directory: https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

What do you think?

**Comment by BergQuester** [comment]
That's my thinking too. My preference is to have projects be as close to clone, build, run as possible and minimize or remove any additional setup. Of course, there are legit exceptions to this such and I would consider repo size with regards to pods to be one of them.

I would also try and minimize the number of binary pods we use as this not only grows repo size faster than source code pods, but also minimizes our visibility into problems. Again, there are going to be times where we have an exception to this.

**Comment by tpalmer** [comment]
Yeah, I agree 💯 

What do you think @jasontwong ?

**Comment by jasontwong** [comment]
Yeah. There was a suggestion to add only the binaries causing the issues to the `.gitignore` file, but I wasn't sure how it would affect BuddyBuild and we were mid-project. It would be nice to do some experiments to see what works with best.

**Comment by tpalmer** [comment]
Closing for now, since this seems to be resolved
